<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="YearlySalaryReciept.aspx.cs" Inherits="SE_Project.Admin.YearlySalaryReciept" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Salary Reciept</title>
    <style type="text/css">
        .auto-style1 {
            width: 100%;
            height: 458px;
        }

        .auto-style2 {
            height: 42px;
            text-align: center;
        }

        .auto-style3 {
            height: 73px;
        }

        .auto-style4 {
            width: 100%;
        }

        .auto-style5 {
            height: 191px;
        }

        .auto-style6 {
            height: 191px;
            width: 517px;
        }

        .auto-style7 {
            text-align: center;
        }

        .auto-style8 {
            height: 157px;
        }

        .auto-style9 {
            height: 64px;
        }

        .auto-style36 {
            width: 137px;
        }

        .auto-style37 {
            width: 156px;
        }
        .auto-style40 {
            width: 190px;
            text-align: center;
        }
        .auto-style42 {
            width: 181px;
            text-align: center;
        }
        .auto-style43 {
            width: 114px;
            text-align: center;
        }
        .auto-style44 {
            width: 117px;
            text-align: center;
        }
        .auto-style45 {
            width: 170px;
            text-align: center;
        }
        .auto-style46 {
            width: 182px;
            text-align: center;
        }
        .auto-style47 {
            width: 187px;
            text-align: center;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:Label ID="ltError" runat="server" Visible="false"></asp:Label>
            <asp:Label ID="Label1" runat="server" Font-Bold="True" Font-Italic="True" Font-Size="XX-Large" Text="Employee Management System"></asp:Label>
            <br />
            <br />
            Your Yearly Salary Slip has been generated successfully.<br />
            <br />
            <asp:Button ID="btnDownload" runat="server" BackColor="#FF9933" Height="31px" Text="Download Invoice" Width="157px" OnClick="btnDownload_Click" />
            <br />
        </div>
        <asp:Panel ID="Panel1" runat="server">
            <table class="auto-style1" border="1">
                <tr>
                    <td class="auto-style2"><strong>Yearly Salary Receipt</strong></td>
                </tr>
                <tr>
                    <td class="auto-style3">
                        <strong>Date</strong> :
                        <asp:Label ID="lblDate" Text='<%# DateTime.Now %>' runat="server"></asp:Label>
                    </td>
                </tr>
                <tr>
                    <td class="auto-style8">
                        <table border="1" class="auto-style4">
                            <tr>
                                <td class="auto-style6">
                                    <table class="auto-style4" border="0">
                                        <tr>
                                            <td class="auto-style36"><strong>Generated By :</strong></td>
                                            <td>&nbsp;</td>
                                        </tr>
                                        <tr>
                                            <td class="auto-style36"><strong>Admin Id :</strong></td>
                                            <td>
                                                <asp:Label ID="lblAdminId" runat="server"></asp:Label>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="auto-style36"><strong>Admin Name :</strong></td>
                                            <td>
                                                <asp:Label ID="lblAdminName" runat="server"></asp:Label>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="auto-style36"><strong>Admin Contact :</strong></td>
                                            <td>
                                                <asp:Label ID="lblAdminContact" runat="server"></asp:Label>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="auto-style36"><strong>Admin Email :</strong></td>
                                            <td>
                                                <asp:Label ID="lblAdminEmail" runat="server"></asp:Label>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                                <td class="auto-style5">
                                    <table class="auto-style4" border="0">
                                        <tr>
                                            <td class="auto-style37"><strong>Employe Id :</strong></td>
                                            <td>
                                                <asp:Label ID="lblEmpId" runat="server"></asp:Label>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="auto-style37"><strong>Employe Name :</strong></td>
                                            <td>
                                                <asp:Label ID="lblEmpName" runat="server"></asp:Label>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="auto-style37"><strong>Employee Dep. :</strong></td>
                                            <td>
                                                <asp:Label ID="lblEmpDep" runat="server"></asp:Label>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="auto-style37"><strong>Employee Design. :</strong></td>
                                            <td>
                                                <asp:Label ID="lblEmpDesign" runat="server"></asp:Label>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="auto-style37"><strong>Employee Contact :</strong></td>
                                            <td>
                                                <asp:Label ID="lblEmpContact" runat="server"></asp:Label>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="auto-style37"><strong>Employee Email :</strong></td>
                                            <td>
                                                <asp:Label ID="lblEmpEmail" runat="server"></asp:Label>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td class="auto-style9">
                                <asp:GridView ID="GridView1" runat="server" ShowHeaderWhenEmpty="true" AutoGenerateColumns="False" CellPadding="4" ForeColor="#333333" GridLines="Both" Width="1103px">
                                    <AlternatingRowStyle BackColor="White" />
                                    <Columns>
                                        <asp:TemplateField HeaderText="Month">
                                            <ItemTemplate>
                                                <asp:Label ID="lblMonth" runat="server" Text='<%# Eval("salary_month") %>'></asp:Label>
                                            </ItemTemplate>
                                        </asp:TemplateField>
                                        <asp:TemplateField HeaderText="Salary">
                                            <ItemTemplate>
                                                <asp:Label ID="lblSalary" runat="server" Text='<%# Eval("sal_amount") %>'></asp:Label>
                                            </ItemTemplate>
                                        </asp:TemplateField>
                                        <asp:TemplateField HeaderText="Travel Allowance">
                                            <ItemTemplate>
                                                <asp:Label ID="lblTravelAllowance" runat="server" Text='<%# Eval("travel_allowance") %>'></asp:Label>
                                            </ItemTemplate>
                                        </asp:TemplateField>
                                        <asp:TemplateField HeaderText="Med Allowance">
                                            <ItemTemplate>
                                                <asp:Label ID="lblMedAllowance" runat="server" Text='<%# Eval("med_allowance") %>'></asp:Label>
                                            </ItemTemplate>
                                        </asp:TemplateField>
                                        <asp:TemplateField HeaderText="Wash Allowance">
                                            <ItemTemplate>
                                                <asp:Label ID="lblWashAllowance" runat="server" Text='<%# Eval("wash_allowance") %>'></asp:Label>
                                            </ItemTemplate>
                                        </asp:TemplateField>
                                        
                                        <asp:TemplateField HeaderText="Leave Deduction">
                                            <ItemTemplate>
                                                <asp:Label ID="lblLeaveDeduction" runat="server" Text='<%# Eval("sal_deduction") %>'></asp:Label>
                                            </ItemTemplate>
                                        </asp:TemplateField>
                                        <asp:TemplateField HeaderText="Net Pay">
                                            <ItemTemplate>
                                                <asp:Label ID="lblNetPay" runat="server" Text='<%# Eval("net_pay") %>'></asp:Label>
                                            </ItemTemplate>
                                        </asp:TemplateField>
                                    </Columns>
                                </asp:GridView>
                                
                        <table>
                                <tr>
                                    <td class="auto-style43"><strong>Total</strong></td>
                                    <td class="auto-style44">
                                        <strong>
                                        <asp:Label ID="lblTotalSalary" runat="server"></asp:Label>
                                        </strong>
                                    </td>
                                    <td class="auto-style40">
                                        <strong>
                                        <asp:Label ID="lblTotalTravelAll" runat="server"></asp:Label>
                                        </strong>
                                    </td>
                                    <td class="auto-style45">
                                        <strong>
                                        <asp:Label ID="lblTotalMedAll" runat="server"></asp:Label>
                                        </strong>
                                    </td>
                                    <td class="auto-style46">
                                        <strong>
                                        <asp:Label ID="lblTotalWashAll" runat="server"></asp:Label>
                                        </strong>
                                    </td>
                                
                                    <td class="auto-style47">
                                        <strong>
                                        <asp:Label ID="lblTotalDeduction" runat="server"></asp:Label>
                                        </strong>
                                    </td>
                                    <td class="auto-style7">
                                        <strong>
                                        <asp:Label ID="lblTotalNetPay" runat="server"></asp:Label>
                                        </strong>
                                    </td>
                                </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td class="auto-style7">&nbsp;</td>
                </tr>
                <tr>
                    <td>Decleration: We declare that there is NO error in this invoice and it is true and accurate.<br />
                        In case if you find any Error or Mistake in this invoice, Please inform <a href="mailto:merehmanali@gmail.com">merehmanali@gmail.com</a><br />
                        <br />
                        THIS IS A COMPUTER GENERATED INVOICE AND DOES NOT REQUIRED SIGNATURE.</td>
                </tr>
            </table>
        </asp:Panel>
    </form>
</body>
</html>
